# Generated by Django 3.2.25 on 2025-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
