# Generated by Django 3.2.25 on 2025-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='category',
            field=models.TextField(default='Blood'),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
