# Generated by Django 3.2.25 on 2025-03-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20250309_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_donoation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='pending')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.donor')),
            ],
        ),
    ]
