# Generated by Django 3.2.25 on 2025-03-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_match_donoation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_donoation',
            old_name='Patient',
            new_name='patient',
        ),
    ]
